version: '3.8'

services:
  # Spring Boot Backend
  backend:
    build:
      context: ./webui-backend
      dockerfile: Dockerfile
    container_name: crossmsg-signing-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8080
    volumes:
      - ./logs:/app/logs
      - ./src/test/resources/iso:/app/src/test/resources/iso:ro
    networks:
      - crossmsg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/CrossMsg-Signing/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ./webui-frontend
      dockerfile: Dockerfile
    container_name: crossmsg-signing-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - crossmsg-network
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: crossmsg-signing-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - crossmsg-network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  crossmsg-network:
    driver: bridge

volumes:
  logs:
    driver: local
