version: '3.8'

name: tsg-crossmsg-signing

services:
  dev:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  gradle-cache:
    name: tsg-crossmsg-signing-gradle-cache 